### ISSUE TITLE
webpack can't extract v0.0.7 anymore

### ISSUE THREAD

**Issue by reneroth** [honeybadger-io/honeybadger-vue#70]
## What are the steps to reproduce this issue?
1. Fresh Laravel installation
2. Install `@honeybadger-io/vue` at v0.0.7
3. Extract `@honeybadger-io/vue` in `webpack.mix.js`
4. `npm run dev`

## What happens?
Build fails

## What were you expecting to happen?
Build not failing

## Any logs, error output, etc?
> ERROR in multi @honeybadger-io/vue
> Module not found: Error: Can't resolve '@honeybadger-io/vue' in '/path/to/project'
>  @ multi @honeybadger-io/vue /js/vendor[0]

## What versions are you using?
**Honeybadger-Vue**: 0.0.7
**laravel-mix**: 4.0.15

## Other notes
This was working in the previous 0.0.6 version

**Comment by reneroth** [comment]
After further testing, the import does not work at all for 0.0.7, even without extracting it - `Can't resolve '@honeybadger-io/vue'` - as soon as I go back to 0.0.6 it works fine again.

**Comment by ssorallen** [comment]
I just ran into this problem as well. The v0.0.7 release does not contain a `dist/` directory, but that is where the package.json is pointing for `"main"`.

**Comment by joshuap** [comment]
@ssorallen thanks, looking into this and will get a new release cut soon.

**Comment by joshuap** [comment]
OK, try 0.0.8 and let me know if that works better for you. This was my fault... I forgot to build before publishing 0.0.7. Sorry about that! Updating build scripts. 😅

**Comment by ssorallen** [comment]
@joshuap Thanks a lot for the release.

**Comment by reneroth** [comment]
Makes me feel better that mistakes happen even to the "big guys" :D thanks for a great product!
