### ISSUE TITLE
Support Vue 3

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-vue#779]
v3 docs: https://v3.vuejs.org

I am not clear on the differences between v2 and v3 yet. It would be nice if we could support both. If not, perhaps we could create a stable branch for v2 when we upgrade to v3. Does it appear that [v2 is still the default on vuejs.org docs](https://vuejs.org)?

Edit: I found this doc useful: https://v3.vuejs.org/guide/migration/global-api.html#a-new-global-api-createapp

**Comment by umarov** [comment]
Locally I modified the code to make it work with Vue 3. Instead of directly modifying the prototype, you need to use `Vue.config.globalProperties.$honeybadger = honeybager`. After making that change, the app boots

https://v3.vuejs.org/guide/plugins.html#writing-a-plugin

**Comment by umarov** [comment]
You could possibly support both by checking if `Vue.protoype` exists. In Vue 3, it's undefined. Vue axios uses app version, but requires semver to be shipped with the library. https://github.com/imcvampire/vue-axios/blob/master/src/index.js

**Comment by joshuap** [comment]
@umarov Thanks for the info!

I think it makes the most sense to create a new branch with Vue 3 support and release it on the `next` npm tag (possibly bump to version 3.x, for parity w/ Vue's major version@next).

I'm looking for someone knowledgeable who I can pay to do this. The code and tests will need to be updated for Vue 3 on the new branch (I can handle release). Let me know if you know of anyone who might be interested. :)

**Comment by umarov** [comment]
I am interested 😊 at work, we are in the process of updating our Vue plugin to 3. We include Honeybadger Vue by default. We need the support for Vue version 3 to be able to release it.

**Comment by joshuap** [comment]
@umarov awesome, I was hoping you'd say that 😁. Could you email me your hourly rate (or preferred payment terms), and give me a ballpark estimate of how long this would take you? josh@honeybadger.io

**Comment by joshuap** [comment]
For the time being, I've applied the [suggested change](https://github.com/honeybadger-io/honeybadger-vue/issues/779#issuecomment-768764526) on the [vue3 branch](https://github.com/honeybadger-io/honeybadger-vue/tree/vue3). Anyone who wants to try out vue3 support can use that branch until we get a release out.

**Comment by 310K** [comment]
Hi,

here is an implementation (pretty naive) of Honeybadger with Vue 3 :

```javascript
import Honeybadger from '@honeybadger-io/js';

export function createHoneybadger(options)
{
    return new VueHoneybadger(options);
}

export class VueHoneybadger
{
    constructor(options = {})
    {
        this._honeybadger = Honeybadger.configure(options);
    }

    install(app)
    {
        app.config.globalProperties.$honeybadger = this._honeybadger;

        const chainedErrorHandler = app.config.errorHandler;

        const extractContext = function(vm)
        {
            let options = typeof vm === 'function' && vm.cid != null ? vm.options : vm._isVue ? vm.$options || vm.constructor.options : vm || {};
            let name = options.name || options._componentTag;
            let file = options.__file;

            return {
                isRoot:         vm.$root === vm,
                name:           name,
                props:          options.propsData,
                parentVnodeTag: options._parentVnode ? options._parentVnode.tag : undefined,
                file:           file
            };
        };

        app.config.errorHandler = (error, vm, info) => 
        {
            this._honeybadger.notify(error, { context: { vm: extractContext(vm), info: info } });

            if(typeof chainedErrorHandler === 'function') 
            {
                chainedErrorHandler.call(app, error, vm, info);
            }
        };
    }

    notify(error)
    {
        this._honeybadger.notify(error);
    }

    setContext(context)
    {
        this._honeybadger.setContext(context);
    }

    addBreadcrumb(message, opts)
    {
        this._honeybadger.addBreadcrumb(message, opts);
    }

    clear()
    {
        this._honeybadger.clear();
    }

    getVersion()
    {
        this._honeybadger.getVersion();
    }
};
```

Maybe it helps someone.

**Comment by subzero10** [comment]
To all interested,

Vue 3 compatibility is complete on [vue](https://github.com/honeybadger-io/honeybadger-vue/tree/vue3) branch (#818).
@joshuap I guess we can close this ticket as soon as we release with the `next` tag?

**Comment by joshuap** [comment]
> @joshuap I guess we can close this ticket as soon as we release with the `next` tag?

Yep, I'll try to get to that on Monday!

**Comment by joshuap** [comment]
We now fully support Vue 3—find the docs here:

https://docs.honeybadger.io/lib/javascript/integration/vue3/

If you encounter new issues w/ the vue3 integration, please create a new issue!
