### ISSUE TITLE
Errors are not logged to the console

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-vue#865]
We've had a few customer support issues related to console logging in development. It seems that by default, Vue logs errors to the console, but errors are not logged to the console when HoneybadgerVue is installed. This is the workaround I've been recommending:

> Our Vue plugin is here:
> 
> https://github.com/honeybadger-io/honeybadger-vue/blob/3fd409efb307e40848a82fe5c5fe702f59517e12/src/index.js
> 
> Something like this might work (this should be configured *before* including Honeybadger):
> 
> ```
> Vue.config.errorHandler = (error, _vm, _info) => {
>   console.log(`Vue error: ${error}`)
> }
> ```

I'd like to research this issue further—what is the default Vue logging behavior? Is there a way we can keep the default logging while also calling HoneybadgerVue's `Vue.config.errorHandler` (and any prior user-configured `Vue.config.errorHandler`, as we currently do?)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_4xq01)

**Comment by nonlocalize** [comment]
The console errors for me are still suppressed when I try this. The same with Vue warnings as well with doing a similar modification to `Vue.config.warnHandler`.

For anyone who has run into the same issues, a hacky workaround is just not loading the HoneyBadgerVue package locally.
```
if (process.env.NODE_ENV !== 'development') {
  Vue.use(HoneybadgerVue, config);
}
```
I know it's not the long-term solution but it at least gets the errors and warnings logging again locally.

**Comment by subzero10** [comment]
@joshuap @nonlocalize It seems that Vue.js will only log errors if there is not `errorHandler` defined.
I looked at Sentry and they copy Vue.js log formatters to log the errors in the same way.
I created this [PR](https://github.com/honeybadger-io/honeybadger-vue/pull/880) that does the same.
Let me know what you think.
