### ISSUE TITLE
@honeybadger-io/vue@next throwing error on setup

### ISSUE THREAD

**Issue by subzero10** [honeybadger-io/honeybadger-vue#962]
## What are the steps to reproduce this issue?
1. npm add @honeybadger-io/vue@next --save

## What happens?
honeybadger-vue.umd.js:102 is throwing this uncaught type error: Cannot set properties of undefined (setting '$honeybadger')

## What were you expecting to happen?
No error

## Any logs, error output, etc?
uncaught type error: Cannot set properties of undefined (setting '$honeybadger')

## Any other comments?
App created using vite

## What versions are you using?
**Package Version:** ^3.0.1

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_70f4x)

**Comment by subzero10** [comment]
Thanks @knobel-dk, I will try it out and come back to you.

**Comment by knobel-dk** [comment]
Hi @subzero10 - Did you manage to reproduce the error? Is it a known bug by now or should I keep spending time trying to fix something on my end? Thanks a lot for the help!

**Comment by subzero10** [comment]
Hey @knobel-dk, sorry for the late response. I've tried to reproduce the error a couple of times so far without any luck. [Here's](https://github.com/subzero10/honeybadger-vue-962) a minimal repo with created with `vite`, `vue3` and `honeybadger-io/vue@next`. Can you help me reproduce it?

**Comment by knobel-dk** [comment]
Thanks @subzero10! I appreciate all your work.

I've added a few commits to the repo so it resembles my setup even more. Still I cannot reproduce it..

I conclude that the issue must be somewhere on my side. I think you can close the issue now and conclude that there is no bug (just wrong usage)..

**Comment by subzero10** [comment]
I'd still like to get to the bottom of this. It's very strange behavior.
I'm thinking the the error probably happens [here](https://github.com/honeybadger-io/honeybadger-vue/blob/vue3/src/index.js#L10) or [here](https://github.com/honeybadger-io/honeybadger-vue/blob/vue3/src/index.js#L11). Can you add some console logs to confirm this? Probably check whether `app` is defined? Or `globalProperties`? FYI, in order to access `globalProperties` you need to pass the root app instance (the result of `createApp`).

**Comment by knobel-dk** [comment]
Hi @subzero10 Wauv, that is true professionalism. I'd be glad to help.

I moved a lot of things around in my codebase and got it working (without understanding why).

I'd be glad to help so canyou add exactly what you need in the minimal repo in terms of passing in the root app?

I will then checkout a commit with the bug from my codebase and share the output with you. Feel free to also add exactly which variables you want to be console logged.

Thanks

**Comment by subzero10** [comment]
Hey @knobel-dk, sorry for the late response here.
I was never able to reproduce this issue. However, we have just released the latest version `@honeybadger-io/vue` (v3.2), which supports vue 2.x and 3.x. The `next` tag is no longer necessary when installing. I added a check inspired from the error you experienced.

Please note that you will have to install `@honeybadger-io/js` as it's a peer dependency from this version onwards.
