### ISSUE TITLE
@honeybadger-io/js dependency not found

### ISSUE THREAD

**Issue by ElVisPL** [honeybadger-io/honeybadger-vue#988]
## What are the steps to reproduce this issue?
1. Install "@honeybadger-io/vue" v3.2.0
2. Serve the application

## What happens?
Trying to upgrade from 1.1.0 to 3.2.0. I'm getting console error:
```
This dependency was not found:

* @honeybadger-io/js in ./node_modules/@honeybadger-io/vue/dist/honeybadger-vue.umd.js

To install it, you can run: npm install --save @honeybadger-io/js
```
Should I also add `@honeybadger-io/js` to the dependencies since v3?

**Comment by subzero10** [comment]
Yes, please do!

Thanks for reporting this!
Since `v3.2`, `@honeybadger-io/js` is a peer dependency. I also created an [issue](https://github.com/honeybadger-io/docs/issues/184) to update documentation.
